### ISSUE TITLE
Scrollview inside bottom sheet

### ISSUE THREAD

**Issue by huy-lv** [nysamnang/react-native-raw-bottom-sheet#1]
Hi, i have tried put a scrollview inside you bottom sheet but it didn't work fine. Could you implement this feature like the below video :D thankyou
https://photos.app.goo.gl/6FgjUm3H6SeWwTBm7

**Comment by NYSamnang** [comment]
@huy-lv Thank for giving me a feedback. I'm gonna implement it to support ScrollView as soon as possible.

**Comment by ManigandanRaamanathan** [comment]
@huy-lv was the scrollView worked or not? Quite confusing

**Comment by huylv-teko** [comment]
@ManigandanRaamanathan  Sorry, it did not work, i missed a  word :D

**Comment by nysamnang** [comment]
@huy-lv @ManigandanRaamanathan  Currently, If you want to use a `ScrollView` inside `RBSheet` you need to set props `closeOnSwipeDown` to `false`. It works, but you just can't use swipe down gesture to close `RBSheet`. Honestly, it's very hard for me to implement `ScrollView` inside `PanResponder`. I spent a lot of hours but still not achieve yet. I really need a contributor who can implement this.

**Comment by huy-lv** [comment]
@nysamnang nice work, i have tried many way too but still not work :D i found some lib on github archived that but it use native bridge. I dont want to use native bridge because i'm using Expo :D

**Comment by ManigandanRaamanathan** [comment]
@nysamnang  could you please share the lib name?

**Comment by ManigandanRaamanathan** [comment]
@nysamnang  thanks for the idea. But having the feature without disabling the closeOnSwipeDown will be better and provides good experience for the users

**Comment by nysamnang** [comment]
@ManigandanRaamanathan Yeah, i'm trying to implement it, I'm not quitting.

**Comment by ManigandanRaamanathan** [comment]
@nysamnang great. I'll give a star for this library. It's quite rare to find such libraries for react native.

**Comment by ManigandanRaamanathan** [comment]
@nysamnang  The idea for scrollView is something like the facebook comment box feature

**Comment by nysamnang** [comment]
@ManigandanRaamanathan You're right, that's my goal XD

**Comment by huy-lv** [comment]
@ManigandanRaamanathan  for you guy https://github.com/prscX/react-native-bottom-action-sheet

**Comment by ManigandanRaamanathan** [comment]
@huy-lv Yes that requires react-native link to make changes with the native codes. Found few people facing build errors. But this version looks clean without requiring native bridge

**Comment by frattle** [comment]
Hello, just a suggestion. Wouldn't it be possible to use both ScrollView and close on swipe down, if you could move listener for "draging down to close" just to bottom part of sheet?
So when closing sheet, you just swipe bottom part and body of sheet could be used as ScrollView.

**Comment by j6workz** [comment]
Wrap the list items rendered inside the ScrollView with **Preassable** or any **Touchables** instead of **View**

It works

**Comment by dishaben9** [comment]
@j6workz It's working for me.

**Comment by NiccoloCase** [comment]
any updates?

**Comment by abdullahSolace** [comment]
instead of doing the **Pressable** or ** Touchables** things apply `flex-grow:1` to your Scrollview.
