### ISSUE TITLE
Tabs inside RB Sheet not scrollable

### ISSUE THREAD

**Issue by 09user** [nysamnang/react-native-raw-bottom-sheet#104]
Hi,

I am using Tab navigator inside RB sheet. But I can't swipe between tabs. Tabs swipe is not working, inside sheet. Can you please suggest on this.

**Comment by mohammad-aaqib-sudo** [comment]
<RBSheet
        ref={taxSheetRef}
        height={300}
        openDuration={250}
        dragFromTopOnly={true} />
Add drag from top only.
