### ISSUE TITLE
The old version Animated is not smooth, Can anyone Update to new Reanimated.

### ISSUE THREAD

**Issue by HoaiHuynh** [nysamnang/react-native-raw-bottom-sheet#109]
I have checked the code in node module, and I saw it use Animated from 'react-native', but after I create the project at 0.63 version, I have a bug, the animated is so lag. Can anyone fix this?

**Comment by joeljerushan** [comment]
This is how it's looks like 💯  before it was fine but not now 👎  someone please check into this issue.

![RPReplay-Final1599987778](https://user-images.githubusercontent.com/10111309/93014397-6b456700-f5ce-11ea-9d09-ee9fc6df503b.gif)

**Comment by nysamnang** [comment]
This library aims to be simple and lightweight without requiring any configuration or external dependencies. If it doesn't meet your needs, I recommend using "@gorhom/bottom-sheet" instead.
