### ISSUE TITLE
Is it possible to configure it so that the user can still interact with the background?

### ISSUE THREAD

**Issue by MorganeAlinai** [nysamnang/react-native-raw-bottom-sheet#110]
Hi,

Nice one ! Pretty awesome features and simple to use. Just one question, is it possible to configure it so that it is still possible to interact with the background while the bottom sheet is on?

I need to make a media player bottom sheet that stays visible while navigating and it is not very clear for me either or not it is possible using react native raw bottom sheet?

Thanks!

**Comment by nysamnang** [comment]
Since the RBSheet is implemented on top of the React Native Modal, we are unable to show or click any elements that are located behind it.
