### ISSUE TITLE
Bottom Sheet is closing when a function is fired inside

### ISSUE THREAD

**Issue by zepskie** [nysamnang/react-native-raw-bottom-sheet#111]
Hi i am new to react native, i am using RBSheet for my app. but when i add the onChangeText function the bottom sheet is closing. i only type one letter then it closes. can someone help me, please

<RBSheet
      ref={refRBDestinationSheet}
      height={60}
      animationType="none"
      openDuration={200}
      customStyles={{ 
        wrapper: { backgroundColor: "rgba(45, 52, 54,0.5)",  },
      draggableIcon: {
        backgroundColor: "grey"
      }
    }}
    >
      <View style={styles.inputContainer}>
        
        <TextInput style={styles.input} autoFocus placeholder="Search your destination..." 
        onChangeText={destination => setDestination(destination)} defaultValue={destination} />
        <MDIcon
          name="send"
          style={[styles.inputIcon, styles.inputIconSend]}
          onPress={() => refRBDestinationSheet.current.close()}
        />
      </View>
    </RBSheet>

**Comment by saeed4u** [comment]
How does your `setDestination` look like?

**Comment by binumathew** [comment]
I have the same problem :{

**Comment by nysamnang** [comment]
Related #129
