### ISSUE TITLE
Web Support 

### ISSUE THREAD

**Issue by DevAhmedRagab** [nysamnang/react-native-raw-bottom-sheet#113]
When i try to run `yarn run web` i got this error

./node_modules/react-native-raw-bottom-sheet/src/index.js 107:6
`Module parse failed: Unexpected token (107:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`
 
     return (
       <Modal
         transparent
         animationType={animationType}

**Comment by MahmonirB** [comment]
I have same issue when I use this package into react-native-web, even with lazy loading this package.

**Comment by nysamnang** [comment]
If it persists in newer versions of react-native, please open a new issue.
