### ISSUE TITLE
close RBSheet => close expo ImageLibrary

### ISSUE THREAD

**Issue by lokomass** [nysamnang/react-native-raw-bottom-sheet#114]
Hi,
When I call "this.RBSheet.close()", this close my sheet, but close too my Expo ImageLibrary...

```
_addPhoto() {
    this.RBSheet.close() // close Sheet and PickerImage, I want keep PickerImage opened
   try {
      let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [1, 1],
        quality: 1
      })
   ...
  }
```

**Comment by haresh4d** [comment]
Have you found any solution? In my case I want to show an Interstitial Ad after closing the RBSheet but when I close the RBSheet it also closes the Interstitial.

**Comment by lokomass** [comment]
Hi
No, i've never find solution...

**Comment by haresh4d** [comment]
Badly need a solution for this. I am also showing interstitial after sheet close but cant do it.

**Comment by haco29** [comment]
Hey, I found a solution for this that may help you. You need to delay the action you want to do after you close the sheet.

_addPhoto() {
    this.RBSheet.close() // close Sheet and PickerImage, I want keep PickerImage opened
_.delay(async () => {
   try {
      let result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [1, 1],
        quality: 1
      })
    }, 300);
   ...
  }
