### ISSUE TITLE
Press Events still not work

### ISSUE THREAD

**Issue by alitele** [nysamnang/react-native-raw-bottom-sheet#119]
Hi,

I am trying to add a touchable opacity inside RBSheet and strangely not press event working. 

I have read the other thread regarding the TouchableOpacity import so my import is from 'react-native' 
Please suggest fix for it.

Thanks,
Ali

**Comment by SamuelSSan28** [comment]
I have the same problem.

**Comment by RafaelA977** [comment]
Also actual for me

**Comment by hoangvu12** [comment]
Same problem, still no solution?

**Comment by SamuelSSan28** [comment]
It's working for me now, I don't remember what i done . But I guess I put all content of the RBSheet inside a view worked for me.

**Comment by cah-chris-scherer** [comment]
I've been noticing that if I use TouchableOpacity directly in the RBSheet it works fine but if I try to render a sub component is when it stops working. Not sure if this is the same issue?

**Comment by nysamnang** [comment]
If it persists in newer versions of react-native, please open a new issue.
