### ISSUE TITLE
ReactNative BottomSheet Navigation error:  undefined is not an object (evaluating 'navigation.navigate')

### ISSUE THREAD

**Issue by samchidi2005** [nysamnang/react-native-raw-bottom-sheet#124]
is:issue is:open Inside the BottomSheet, I changed 'Drawing' link to 'HomeScreen' link, just like this "onPress={() => navigation.navigate('HomeScreen')}" and clicked on it to navigate to HomeScreen, but ends up getting this error:  undefined is not an object (evaluating 'navigation.navigate'). I have tried using  "const navigation = useNavigation();" to solve it but to no avail. Please I need your help. Thanks.

**Comment by samchidi2005** [comment]
<BottomSheet ref={ref => {
                    this.BottomSheetRef = ref; 
                    
                    }} 
                    closeOnDragDown
                    customStyles={{
                    container: {
                        borderTopLeftRadius: 10,
                        borderTopRightRadius: 10
                    }
                    }}
                    
                   height={350} 
                >
                    <View style={styles.moreListContainer}>
                        <Text style={styles.moreListTitle}>MORE LIST</Text>
          
                        <TouchableOpacity style={styles.listButton} onPress={() => navigation.navigate('HomeScreen')}>
                            <ATIcon name='questioncircleo' color="#444" size={21} />
                            <Text style={styles.listLabel}>Home</Text>
                            <FAIcon name='angle-right' color="grey" size={25} style={styles.rightSideIconStyle} />
                        </TouchableOpacity>
                     </View>
</BottomSheet>

**Comment by adekunle11** [comment]
Try `onPress={({ navigation }) => navigation.navigate('HomeScreen')}`

**Comment by nysamnang** [comment]
I suggest checking the `navigation.navigate()` method from React Navigation as this issue may not be related to RBSheet.
