### ISSUE TITLE
Preset issue

### ISSUE THREAD

**Issue by markronquillo** [nysamnang/react-native-raw-bottom-sheet#13]
Hi, good day,

I am experiencing this error during build in android (I haven't checked iOS yet).

`Couldn't find preset "module:metro-react-native-babel-preset`

Has anyone experienced this before? I tried installing metro-react-native-babel-preset as well but it didn't solve it. 

I am using RN0.51 btw.

Thanks.

**Comment by nysamnang** [comment]
@markronquillo That's weird! Maybe your project is conflicted with other lib not mine.

**Comment by nysamnang** [comment]
@markronquillo Have you solved this error yet?

**Comment by markronquillo** [comment]
Not yet, but I think upgrading the RN version will it. so yeah

**Comment by joakin8** [comment]
Hi guys, I am suffering now the same error as @markronquillo, I have RN 0.59.10 on my project, and the error says that module:metro-react-native-babel-preset is not found in this library. It is rare, because I already have that preset installed in my project, thoughts?

Thanks!
