### ISSUE TITLE
Touch events not working on IOS simulator

### ISSUE THREAD

**Issue by upngo** [nysamnang/react-native-raw-bottom-sheet#130]
I updated react native from 0.59 to 0.63 and touch events now don't work on the iOS simulator. 
Still using react-native-raw-bottom-sheet@2.2.0

Touch events on the mask never work (ie the closeOnPressMask option)
Touch events on the tray body never fire
Dragging the tray down works rarely.

I've tried internally using TouchableOpacity from both react-native and react-native-gesture-handler.

Everything works on my android emulator (level 30). Will test on an iOS device shortly.

**Comment by zakve** [comment]
Same issue. Only happens on the iOS simulator. On iOS device or Android works fine.
"react-native": "0.64.1",
"react-native-raw-bottom-sheet": "^2.2.0",
iOS simulator: iPhone 12 - iOS 14.5

**Comment by Brenndoerfer** [comment]
Issue still persists

**Comment by muzammil-kt** [comment]
any fix?

**Comment by nysamnang** [comment]
If it persists in newer versions of react-native, please open a new issue.
