### ISSUE TITLE
Add statusBarTranslucent on Modal

### ISSUE THREAD

**Issue by jiwooIncludeJeong** [nysamnang/react-native-raw-bottom-sheet#132]
This one shows not fullscreen Bottom Sheet when Android is on Immersive Mode.
So what about add statusBarTranslucent option at Modal component? I want to open PR but I don't have permission about to request it.

Below image is the difference of that option. Upper is no option, below one is on.

![image](https://user-images.githubusercontent.com/63336958/118922301-c0632500-b974-11eb-9dda-824b869014ad.png)
![image](https://user-images.githubusercontent.com/63336958/118922316-c822c980-b974-11eb-8e4f-706effae1e55.png)

**Comment by nysamnang** [comment]
Resolved #90
