### ISSUE TITLE
How to mock the react-native-raw-bottom-sheet ??

### ISSUE THREAD

**Issue by PriyaMani-yara** [nysamnang/react-native-raw-bottom-sheet#133]
![image](https://user-images.githubusercontent.com/77480598/119538911-2957fc00-bdbe-11eb-8940-52d0a253992d.png)
jest.mock("react-native-raw-bottom-sheet", () => ({
  ...jest.requireActual("react-native-raw-bottom-sheet"),
 onOpen: jest.fn(),
 }))

Please does any one have any idea?

**Comment by Sub-Zero-1** [comment]
Any solution to this?

**Comment by Sub-Zero-1** [comment]
Maybe that helps someone: 
`const setModalVisible = jest.spyOn(RBSheet.prototype, 'setModalVisible');`

**Comment by MorenoMdz** [comment]
Any ideas on how to do this?

**Comment by Abdulsami-Metafic** [comment]
> ![image](https://user-images.githubusercontent.com/77480598/119538911-2957fc00-bdbe-11eb-8940-52d0a253992d.png) jest.mock("react-native-raw-bottom-sheet", () => ({ ...jest.requireActual("react-native-raw-bottom-sheet"), onOpen: jest.fn(), }))
> 
> Please does any one have any idea?

Hello @PriyaMani-yara Can you please let me know how did you fixed it?

**Comment by Abdulsami-Metafic** [comment]
> Any ideas on how to do this?

Are you able to solve this?

**Comment by hetabytes** [comment]
Hello 
I have found one of the solutions for this 
You need to take package out of the node modules and then pass reference path of the package 
It will resolve the issue also don't forget to mock the function 

`jest.mock("react-native-raw-bottom-sheet", () => ({
    ...jest.requireActual("react-native-raw-bottom-sheet"),
    onOpen: jest.fn(),
}));`

**Comment by harit2305** [comment]
> Hello I have found one of the solutions for this You need to take package out of the node modules and then pass reference path of the package It will resolve the issue also don't forget to mock the function
> 
> `jest.mock("react-native-raw-bottom-sheet", () => ({ ...jest.requireActual("react-native-raw-bottom-sheet"), onOpen: jest.fn(), }));`

its working thanks @hetabytes
