### ISSUE TITLE
Background Overlay is not available

### ISSUE THREAD

**Issue by Brad19** [nysamnang/react-native-raw-bottom-sheet#134]
hi @nysamnang 

We have a requirement where we need to add a background overlay for the bottom-sheet which at this point of time can only be done outside the component and not within the component. And further when bottom sheet opens, it should show the backgroundOverlay and upon tapping the backgroundOverlay, it should not close the bottom sheet, but rather disable/close the backgroundOverlay. I've update the code to get that working and its in my local. If you think, it would be useful, Pls let me know and grant me access, so i can raise a PR. And  you can take it accordingly

- Brad

**Comment by abhilashiic** [comment]
Right @Brad19, I am also feeling the requirement of it.

**Comment by abhilashiic** [comment]
One solution I got is

```
customStyles={{
    wrapper: {
        backgroundColor: "rgba(0,0,0,0.6)",
        width: "100%",
        alignSelf: "center"
    },
}}
```
