### ISSUE TITLE
RBSheet takes too long to open first time

### ISSUE THREAD

**Issue by vipulbuoyancy** [nysamnang/react-native-raw-bottom-sheet#138]
Hello, 

RBSheet takes too long to open for first time in the application, Please have a look at attached video.

Please help me to solve this issue.

Thank you.

https://user-images.githubusercontent.com/80636669/147531331-68aa03c4-e77e-4270-a375-f668138a9dc3.mp4

**Comment by fukemy** [comment]
i think.  https://github.com/gorhom/react-native-bottom-sheet is better, this lib seem dead after 2. years without code update
