### ISSUE TITLE
Toast when bottom sheet is open

### ISSUE THREAD

**Issue by rdgoutiyama** [nysamnang/react-native-raw-bottom-sheet#139]
How to make toast and others overlay's bring to front of bottom sheet?

I started using react-native-toast-message and native Toast and both stay behind of opened bottom sheet.

**Comment by geydson** [comment]
@rdgoutiyama  I have the same problem, did you manage to solve it?

**Comment by rdgoutiyama** [comment]
> @rdgoutiyama I have the same problem, did you manage to solve it?

I duplicated the following code in render function in my specific screens/scenarios:

```
    <Toast ref={(ref) => Toast.setRef(ref)} />
``` 

and I use Toast.show function to show.

**Comment by nysamnang** [comment]
Since the RBSheet is implemented on top of the React Native Modal, we are unable to show or click any elements that are located behind it. Anyway, I think this solution #147 can be helpful.
