### ISSUE TITLE
Resolving values on Close 

### ISSUE THREAD

**Issue by 32teeths** [nysamnang/react-native-raw-bottom-sheet#14]
Whenever the bottom sheet closes , the onClose event is triggered . I am trying to resolve a value that I passed while closing to the onClose event . 

How to ? 

Or in a way

  <RBSheet
                    onClose={(args) => {
                        console.log(args);
                    }}

// Inner component closed the bottom sheet with ref 
/>

I am trying to get the `args`

**Comment by nysamnang** [comment]
@32teeths 
```
<RBSheet
onClose={() => {
console.log(your_args);
}}

// Inner component closed the bottom sheet with ref
/>
```
 You don't need to put `args` inside `(args) => {}`. If you put like this it means you wish to get `args` from `RBSheet` not yours.
