### ISSUE TITLE
Default Opening

### ISSUE THREAD

**Issue by Milan-rawat** [nysamnang/react-native-raw-bottom-sheet#145]
Bottom-Sheet can only be opened when firing a function refRBSheet.current.open(),  it should have a default opening boolean. 
If there is already that feature please tell me.

**Comment by mobeenali12** [comment]
Hi @Milan-rawat , did you find the solution ?

**Comment by nysamnang** [comment]
I think we don't need a default opening, while we can call the `open()` method whenever needed to show the RBSheet.
