### ISSUE TITLE
how to make other Component front of rbsheet 

### ISSUE THREAD

**Issue by echolove38** [nysamnang/react-native-raw-bottom-sheet#147]
I write a loading component , 
and try to show loading when click the button in the rbsheet, 
but the loading is always back of the rbsheet, 
even if I set zIndex/elevation much high
![image](https://user-images.githubusercontent.com/12425497/183035578-bcdd6088-5573-469e-b324-0107067b1327.png)

**Comment by JedrekDabrowski** [comment]
You can add customStyles to RBSheet: 
```
    <RBSheet
      customStyles={{
        wrapper: styles.sheetWrapper,
        container: styles.sheetContainer,
      }}...
```

in styles.sheetContainer just add   `overflow: 'visible',`

**Comment by minhdandys2** [comment]
" in styles.sheetContainer just add overflow: 'visible' " not working
