### ISSUE TITLE
Please type props with 'PropsWithChildren'

### ISSUE THREAD

**Issue by fkranenburg** [nysamnang/react-native-raw-bottom-sheet#148]
Our typescript compiler is complaining about `  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RBSheet> & Readonly<RBSheetProps>'.` and it looks like this is because of RBSheetProps is missing PropsWithChildren

**Comment by guy-shahine** [comment]
This PR fixes the issue https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/146

I've used `patch-package` for now

**Comment by gabk17** [comment]
well, it did not @guy-shahine

**Comment by gabk17** [comment]
well, it did not yet, @guy-shahine you guys have to merge it

**Comment by rick427** [comment]
Am still having the same issue on my RN typescript project.

**Comment by guy-shahine** [comment]
@gabk17 I don't have to proper permissions to merge, I approved the PR and waiting for the repo maintainers to merge and release a patch

**Comment by alalfakawma** [comment]
Need this fixed. Hope patch will be released soon.

**Comment by Arvo-palma** [comment]
Not fixed yet.

**Comment by rowbot-weisguy** [comment]
@nysamnang please consider merging this PR. It would solve a simple type definition issue for many people without altering any functionality. Thanks!

**Comment by nysamnang** [comment]
Merged #146
