### ISSUE TITLE
Side Animation slides in the background

### ISSUE THREAD

**Issue by timothystewart6** [nysamnang/react-native-raw-bottom-sheet#15]
Hi.  Nice component! I am seeing an issue with the slide animation where the background also slides in along with the bottom sheet.  From the example screenshots, it looks like the background should fade in - in both scenarios (`slide` and `fade`) however it seems like the transparent background slides in along with the bottom sheet when it is set to `slide`.

```
  <RBSheet
          closeOnDragDown
          ref={ref => {
            this.RBSheet = ref
          }}
          height={360}
          duration={300}
          animationType="slide"
          customStyles={{
            container: {
              ...styles.header,
            },
          }}
        >
          {this.renderBottomSheet()}
   </RBSheet>
```

**Comment by timothystewart6** [comment]
I think this just might be a simulator / dev issue or a `duration` setting issue.  I will see if I can narrow it down or just close the issue.

**Comment by nysamnang** [comment]
@timothystewart6 There is nothing wrong. If you set props `animationType="slide"` it means the background animation is gonna slide up along with the bottom sheet. I'm not recommend to use `slide` but i'm sure in some cases user will need it that's why we should have this props for user choices.

**Comment by timothystewart6** [comment]
Thanks for the clarification!  Working as designed :)  I can totally see a use case for this now that you mention it, however not for mine.  Thank you!

**Comment by Gutyn** [comment]
@timothystewart6 did you find a way to do the sliding correctly? maybe separate the background animations somehow?
