### ISSUE TITLE
Flat list item click not working on first click

### ISSUE THREAD

**Issue by FourVectorDiv333** [nysamnang/react-native-raw-bottom-sheet#150]
I am using a flat list inside rbsheet and my item clicks are not working on the first touch. I need to click twice. Any solution?

**Comment by IKTANIM** [comment]
Add this property `keyboardShouldPersistTaps={'handled'}` in `FlatList` and also add this property `keyboardShouldPersistTaps={'handled'}` in all the parent `ScrollView` then it will work.
