### ISSUE TITLE
Serious Delay on open

### ISSUE THREAD

**Issue by Venipa** [nysamnang/react-native-raw-bottom-sheet#16]
https://i.mavis.moe/f/MKd8EaIzJG/2019-06-04-18-15-39.mp4

Recorded it

**Comment by nysamnang** [comment]
@Venipa We didn't set any time delay methods to bottom sheet. I'm pretty sure it has issue with your device performance. Have you tried turning debug mode off or testing with other devices?

**Comment by Venipa** [comment]
im pretty sure its not a performance issue with my devices, im not using a vm
https://i.mavis.moe/f/phnckmvhPr/2019-08-26-19-45-25.mp4

**Comment by Venipa** [comment]
so i've found the issue, the duration does not actually set the animation duration it delays the opening.
so if you set the duration to 1000ms the sheet would open once the delay is done
