### ISSUE TITLE
how to disable draggableIcon ?

### ISSUE THREAD

**Issue by furqan-hassan110** [nysamnang/react-native-raw-bottom-sheet#160]
<RBSheet
          ref={(ref: any) => {
            RBSheetRef.current = ref;
          }}
          animationType={'fade'}
          height={350}
          closeOnDragDown={true}
          closeOnPressMask={true}
          customStyles={{
            wrapper: {
              backgroundColor: 'transparent',
            },
            draggableIcon: {
              backgroundColor: Colors.buttonlogin,
            },
            container: {
              borderTopLeftRadius: 10,
              borderTopRightRadius: 10,
            },
          }}
        >
          <View style={style.card}>
            <FormattedMessage style={style.sheetheader} {...messages.sheetheadlabel}></FormattedMessage>
          </View>
        </RBSheet>

**Comment by eng-naveed** [comment]
A quick hack
draggableIcon: {
display: 'none'
},

**Comment by Yasir12598** [comment]
```
customStyles={{
draggableIcon: {
width:0,
                    height:0,
                    margin:0,
},
}}
```
