### ISSUE TITLE
fix the height error it is not working 

### ISSUE THREAD

**Issue by Beki78** [nysamnang/react-native-raw-bottom-sheet#190]
I use the code from the npm I have installed all of the packages but it is saying style property 'height' is not supported by native animated module

**Comment by abhishekv-gloify** [comment]
Hi @Beki78 ,  i am also getting same error. have you found any solution.

**Comment by gatiendidry** [comment]
Hello, I have the same problem

**Comment by Beki78** [comment]
hi @abhishekv-gloify  nope but I use another package that works [https://www.npmjs.com/package/@gorhom/bottom-sheet](url)

**Comment by Beki78** [comment]
> Hi @Beki78 , i am also getting same error. have you found any solution.

hi @abhishekv-gloify nope but I use another package that works [https://github.com/nysamnang/react-native-raw-bottom-sheet/issues/190#issuecomment-2273571385](url)

**Comment by iamharisdev** [comment]
Did anyone found a solution? caus I'm still getting an error
