### ISSUE TITLE
BUG: Modal position

### ISSUE THREAD

**Issue by VadimOsovsky** [nysamnang/react-native-raw-bottom-sheet#22]
At times the modal would appear higher than usual causing this weird effect (see the screenshots)
![lkR0ycdwaOc](https://user-images.githubusercontent.com/39897981/61436148-d64fcb00-a942-11e9-8e23-27c953ceae4e.jpg)
![a8EnO4KDhCc](https://user-images.githubusercontent.com/39897981/61436149-d6e86180-a942-11e9-8cea-474b0afe7111.jpg)

**Comment by nysamnang** [comment]
@VadimOsovsky That's weird! I just have published a new version, so let's upgrade to the latest one. If you still have this problem please kindly open it again.

**Comment by predescu** [comment]
I have the same problem. I think the space there it's from the software navigation bar on Android.
