### ISSUE TITLE
Drawer cannot be closed when rendered

### ISSUE THREAD

**Issue by dowanabe** [nysamnang/react-native-raw-bottom-sheet#23]
i am trying to close the drawer after i click on an image that is located within the drawer. the this.RBSheet.close() isn't working. this is called inside of a function that is dynamically adding images and using the implementation that you suggested in your comments in issue 10. any ideas on how to make this work?

**Comment by IntelliJAbhishek** [comment]
its also cannot be closed when we are using live reload its not good

**Comment by dowanabe** [comment]
@nysamnang any updates here?

**Comment by bomanimc** [comment]
Also experiencing this issue with closing on live reload. Please help @nysamnang!

**Comment by IntelliJAbhishek** [comment]
problem with react native modal cant be fixed untill modal is not fixed by official RN

**Comment by nysamnang** [comment]
@IntelliJAbhishek Yes, you're right!

**Comment by nysamnang** [comment]
@dowanabe I have added the example code in this repo, so let's see the example for more clarity of using dynamic bottom sheet.
