### ISSUE TITLE
cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by dowanabe** [nysamnang/react-native-raw-bottom-sheet#25]
the this.RBSheet.open() and close() methods are not working. The open method works when i wrap it in a map function and use this[RBSheet + key].open() but otherwise i get the error "cannot read property 'open' of undefined. Any ideas on how to resolve?

**Comment by shamoons** [comment]
I have the same issue

**Comment by bachbonglong** [comment]
I have the same issue too . Any solution ?
