### ISSUE TITLE
How to disable the backdrop? 

### ISSUE THREAD

**Issue by madeinquant** [nysamnang/react-native-raw-bottom-sheet#26]
Thank for your contribution. Would you advise me? Is it possible to disable the backdrop in the "customStyles"?

**Comment by karpokate** [comment]
just add to your element custom style: 
          customStyles={{
              wrapper : { 
                 backgroundColor: "" }
          }}

**Comment by bomanimc** [comment]
@karpokate's solution worked for me. Maybe this should be added to the README?

**Comment by nysamnang** [comment]
@madeinquant 
```
customStyles={{
  wrapper: {
    backgroundColor: "transparent" // Any color
  }
}}
```

**Comment by akbari6776** [comment]
> @madeinquant
> 
> ```
> customStyles={{
>   wrapper: {
>     backgroundColor: "transparent" // Any color
>   }
> }}
> ```

Hi
I'm using RBSheet and thats height set to part off screen from bottom, But another part of screen has under the backdrop.
how can i disable backdrop ? not only background color
