### ISSUE TITLE
Events not responding in Android, works on IOS

### ISSUE THREAD

**Issue by ayodejilawrence1** [nysamnang/react-native-raw-bottom-sheet#29]
Press events aren't fired on Androis Devices even though they work fine on IOS. See stub below

<RBSheet
                        ref={ref => {
                            this.RBSheet = ref;
                        }}
                        height={180}
                        duration={250}
                        animationType={"none"}
                        closeOnDragDown={true}
                        customStyles={{
                            container: {
                                //justifyContent: "left",
                                alignItems: "center",
                                borderRadius: 16
                            }
                        }}
                    >

                        <View style={{ paddingTop: 30 }}>
                           <TouchableOpacity onPress={() =>this.search()}>
                                <ListTitle>
                                    <ListIcon>
                                        <Ionicons
                                            name="ios-search"
                                            size={30}
                                            color="#939BA1"
                                        />
                                    </ListIcon>
                                    <ListSubTitle>Search</ListSubTitle>
                                </ListTitle>
                            </TouchableOpacity>

                            <TouchableOpacity onPress={() =>this.logout()}>
                                <ListTitle>
                                    <ListIcon>
                                        <Ionicons
                                            name="ios-log-out"
                                            size={30}
                                            color="#939BA1"
                                        />
                                    </ListIcon>
                                    <ListSubTitle>Logout</ListSubTitle>
                                </ListTitle>
                            </TouchableOpacity>
                        </View>

                    </RBSheet>

**Comment by nysamnang** [comment]
@ayodejilawrence1 @pbombo I just have published a new version, so let's upgrade to the latest one. If you still have this problem please kindly open it again.

**Comment by sjonchhe** [comment]
I think the problem still persists.Has anybody else faced the problem in the latest update aswell??

**Comment by Sharqiyem** [comment]
> I think the problem still persists.Has anybody else faced the problem in the latest update aswell??

I have the same
Is anyone found how to fix it?

**Comment by jennifer-elyse** [comment]
I'm looking for a workaround as well
