### ISSUE TITLE
Could not find a declaration file for module 'react-native-raw-bottom-sheet'.

### ISSUE THREAD

**Issue by chrystoffer** [nysamnang/react-native-raw-bottom-sheet#3]
When I tried to use this module, I got this error message.
To use, I had to create a file in "_/node_modules/react-native-raw-bottom-sheet/src/types/any.d.ts_" and declare
`declare module 'react-native-raw-bottom-sheet'`

If someone has the same problem.

**Comment by Grohden** [comment]
related to #8
