### ISSUE TITLE
Keyboard overlay on iOS inputs

### ISSUE THREAD

**Issue by ramonvermeulen** [nysamnang/react-native-raw-bottom-sheet#30]
When I put an input in my raw bottom sheet the keyboard will render on top of the raw bottom sheet on iOS. On android it is all working fine.

**Comment by FelipeBerrios** [comment]
Hi, do you have any examples of how to solve this problem? Thank you

**Comment by nysamnang** [comment]
@ramonvermeulen @shubhank12 @FelipeBerrios This issue has already fixed, please download the latest version.
