### ISSUE TITLE
How to make it similar to google map

### ISSUE THREAD

**Issue by ansarikhurshid786** [nysamnang/react-native-raw-bottom-sheet#36]
Currently I am using [rn-bottom-sheet](https://github.com/matinzd/rn-bottom-sheet) but it has some issue and not bottom animation. 

I tried this library. it is really perfect. Only one thing is missing. when i open bottom sheet, user loose focus from main view.

how can i achieve ?

**Comment by nysamnang** [comment]
@ansarikhurshid786 `RBSheet` is implementing on react native `Modal`. When the Modal opens it's gonna cover all the screen. As this behavior, I can say that your issue absolutely won't be fixed, and sorry for this inconvenient.
