### ISSUE TITLE
Not working with ScrollView

### ISSUE THREAD

**Issue by Foskas** [nysamnang/react-native-raw-bottom-sheet#40]
Hi, is it possible to have RBSheet with closeOnDragDow and a ScrollView as child ?

I've tried and when I drag down, the scroll view does not responde, but only the RBSheet is reacting to the event.

Code: 
```
    <RBSheet
      ref={ref => {
        BottomSheetRef = ref
        props.onReceiveRef(ref)
      }}
      animationType="fade"
      closeOnDragDown={true}
    >
            <ScrollView
              bounces={false}
              showsVerticalScrollIndicator={false}
              style={styles.Scroll}
              contentContainerStyle={styles.ScrollContentContainer}
              nestedScrollEnabled={true}
            >
              {this.props.myUsage.serviceBalanceList.map((item: UsageItem, key: number) =>
                // item.addonType && item.bucketName
                true ? (
                  <View key={key} style={styles.ItemView}>
                    <Text style={styles.PrimaryText}>{item.bucketName || 'asdasd'}</Text>
                    {item.toDate ? (
                      <Text style={styles.SecondaryText}>{`Expires on ${item.toDate}`}</Text>
                    ) : null}
                  </View>
                ) : null
              )}
            </ScrollView>
</RBSheet>
```

Any help would be great!
Thanks!!

**Comment by nysamnang** [comment]
Hello @Foskas, currently `RBSheet` doesn't support this feature yet. If we use `ScrollView` inside `RBSheet` we cannot drag the `ScrollView`'s content down to close bottom sheet thus I created a draggable area on the top instead. I've tried implementing many times but no luck to achieve this.
I'll really appreciate if someone could help me to achieve this feature!!!

**Comment by iamshadmirza** [comment]
How you created that scrollable bottom sheet? @nysamnang

**Comment by Ksiner** [comment]
Seems like drag event is not even triggered on ScrollView, like it's content is not responding on touches or drag or anything else. For some reason this behaves correctly if ScrollView children is wrapped in TouchableOpacity. Then when we drag on that wrapped children ScrollView is respond and scrolls in any direction. Maybe that happens because TouchableOpacity is taking event first and that somehow tells ScrollView that its content is touched so it have to respond. Hope that helps somehow.

**Comment by johhansantana** [comment]
I was able to achieve scroll inside the drawer by adding the `<ScrollView>` as direct children followed by a `<TouchableOpacity>` with the content inside it

like this:
```
<ScrollView>
  <TouchableOpacity activeOpacity={1}>
    ...
  </TouchableOpacity>
</ScrollView>
```

for some reason, it doesn't work with `<View>` but does so with `<TouchableOpacity>`

**Comment by ManuEpi** [comment]
Very nice @johhansantana it's working thanks

**Comment by musthafa-pa** [comment]
Yeah, @johhansantana  It worked when I wrapped it inside a touchable opacity. Thanks, man.

**Comment by umerdogar** [comment]
thanks @johhansantana

**Comment by thuhuong1995** [comment]
Thanks @johhansantana , it's working

**Comment by ivanpagac** [comment]
I would not consider it as working because if you scroll to bottom you are not able to scroll to top

**Comment by abdullahSolace** [comment]
instead of doing the **Pressable** or **Touchables** things apply `flex-grow:1` to your Scrollview.

**Comment by alimohsinz** [comment]
just set 
dragOnContent={false}
and scroll will start working
