### ISSUE TITLE
How to work with functional components?

### ISSUE THREAD

**Issue by gsbrunichaki** [nysamnang/react-native-raw-bottom-sheet#41]
Hi,

I'm trying to implement the RBSheet into a funcional component, but I failed.

My code:

> export default function AddItems() {
>   return (
>     <Container>
>       <ProgressBar />
>       <Bottom>
>         <Button
>           title="OPEN BOTTOM SHEET"
>           onPress={() => {
>             RBSheet.open();
>           }}
>         />
>       </Bottom>
>       <RBSheet
>         ref={ref => {
>           RBSheet = ref;
>         }}
>         height={300}
>         duration={250}
>         customStyles={{
>           container: {
>             justifyContent: 'center',
>             alignItems: 'center',
>           },
>         }}
>       >
>         <Text>Test</Text>
>       </RBSheet>
>     </Container>
>   );
> }

**Comment by nickmccomb** [comment]
```
const Sheet = useRef(null) // top of component

return (
    <RBSheet ref={Sheet} >
        <>< />
    </RBSheet>
)
```

Then, when you want to open close, in any function:
Sheet.current.open() or Sheet.current.close()

**Comment by gsbrunichaki** [comment]
Perfect! Thank you
