### ISSUE TITLE
[Question] will the sheet will present itself over app‘s tab bar?

### ISSUE THREAD

**Issue by oferRounds** [nysamnang/react-native-raw-bottom-sheet#42]
I’m using `react-native-navigation`

Thank you for this library!

**Comment by nysamnang** [comment]
@oferRounds Sure, because RBSheet is implementing on top of [React Native Modal](https://facebook.github.io/react-native/docs/modal).

**Comment by kkureli** [comment]
how to avoid this ? i want make bottom tab bar visible on bottom sheet
