### ISSUE TITLE
When active closeOnDragDown, ScrollView doesn't work

### ISSUE THREAD

**Issue by leoceolin** [nysamnang/react-native-raw-bottom-sheet#48]
When i turn on the closeOnDragDown props, ScrollView stops working inside bottom sheet navigator. 
This is my code.
To reproduce demo, can use https://github.com/nysamnang/react-native-raw-bottom-sheet/blob/master/example/static.json, data wich is shown came in json format.
`
import React from 'react'

import MapView, {Marker} from 'react-native-maps'
import {View, Alert, StyleSheet, Text, ScrollView} from 'react-native'

import RBSheet from 'react-native-raw-bottom-sheet'

class Mapa extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      region: {
        latitude: -19.9203661, // 19.9203661 22.2087173
        longitude: -43.9210439, // 43.9210439 54.8390909
        latitudeDelta: 0.04, //  0.0922
        longitudeDelta: 0.04, // 0.0421
      },
      pontosMarker: [],
      pontos: [],
      pontoSelecionado: [],
      nomePonto: '',
    }
  }

  markerDetails = async pontoNome => {
    this.state.pontoSelecionado = []
    Reactotron.log('pontoNome', pontoNome)

    // Reactotron.log('pontoSelecionado INI', this.state.pontoSelecionado)

    const pointAux = await this.state.pontos.filter(
      res => res.nomePonto === pontoNome
    )

    Reactotron.log('pointAux', pointAux)

    pointAux.map(res => {
      this.setState({
        pontoSelecionado: [...this.state.pontoSelecionado, res],
      })
    })

    this.setState({nomePonto: pontoNome})

    this.RBSheet.open()
  }

  render() {
    return (
      <View style={{flex: 1}}>
        <MapView
          style={{flex: 1}}
          mapType='satellite'
          initialRegion={this.state.region}
          cacheEnabled={false}
          region={this.state.region}>
          {this.state.pontosMarker.map(item => {
            return (
              <Marker
                key={item.id}
                title={item.title}
                description={item.description}
                coordinate={item.coordinates}
                onPress={() => {
                  this.markerDetails(item.nomePonto)
                }}
              />
            )
          })}
        </MapView>

        <RBSheet
          ref={ref => {
            this.RBSheet = ref
          }}
          closeOnDragDown
          customStyles={{
            mask: {backgroundColor: 'transparent'},
            container: {
              elevation: 100,
              height: 350,
              borderTopLeftRadius: 20,
              borderTopRightRadius: 20,
              backgroundColor: '#f7f5eee8',
            },
            draggableIcon: {
              backgroundColor: '#00000040',
            },
          }}>
          <ScrollView>
            <View style={styles.messageContainerTitle}>
              <Text style={styles.messageTitle}>{this.state.nomePonto}</Text>
            </View>

            <View>
              {this.state.pontoSelecionado.map(res => {
                const coords = JSON.parse(res.coordinates)
                const date = this.formatDate(res.date)
                if (res.fullInfo.tipoNC !== undefined) {
                  return (
                    <View key={res.date} style={styles.messageContainer}>
                      <View style={styles.message}>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Fazenda:</Text>{' '}
                          {res.fazenda}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Talhão:</Text>{' '}
                          {res.field}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Data:</Text> {date}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Latitude:</Text>{' '}
                          {coords.lat}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Longitude:</Text>{' '}
                          {coords.lon}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Praga:</Text>{' '}
                          {res.pragueName}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>
                            Plantas analisadas:
                          </Text>{' '}
                          {res.plantasAtacadas}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>
                            Plantas atacadas:
                          </Text>{' '}
                          {res.plantasAnalisadas}
                        </Text>
                      </View>
                      <View style={styles.lineWithPlants} />
                    </View>
                  )
                } else {
                  return (
                    <View key={res.date} style={styles.messageContainer}>
                      <View style={styles.message}>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Fazenda:</Text>{' '}
                          {res.fazenda}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Talhão:</Text>{' '}
                          {res.field}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Data:</Text> {date}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Latitude:</Text>{' '}
                          {coords.lat}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Longitude:</Text>{' '}
                          {coords.lon}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Praga:</Text>{' '}
                          {res.pragueName}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Quantidade:</Text>{' '}
                          {res.quantity}
                        </Text>
                      </View>
                      <View style={styles.line} />
                    </View>
                  )
                }
              })}
            </View>
          </ScrollView>
        </RBSheet>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },

  line: {
    marginTop: 5,
    borderBottomWidth: 1,
    borderColor: '#000',
  },

  lineWithPlants: {
    marginTop: 30,
    borderBottomWidth: 1,
    borderColor: '#000',
  },

  messageContainerTitle: {
    paddingLeft: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    justifyContent: 'center',
    flexDirection: 'row',
    // backgroundColor: '#f7f5eee8',
    backgroundColor: 'rgba(247, 245, 238, 0.1)',
  },

  messageTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
  },

  messageContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },

  message: {
    height: 145,
    paddingLeft: 20,
  },
})

export default Mapa
`

**Comment by ansarikhurshid786** [comment]
got solution ?

**Comment by leoceolin** [comment]
not yet, i disable scroll and put a button to close or close on press back button device.
![image](https://user-images.githubusercontent.com/37599840/73840512-b0aae600-47ee-11ea-9281-c20548964974.png)

**Comment by ansarikhurshid786** [comment]
Thank you so much for your response. it looks good. i am also showing map.

**Comment by rhrahul** [comment]
check this,
https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/50/files

**Comment by aozfen** [comment]
> check this,
> https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/50/files

solved the problem

**Comment by leoceolin** [comment]
> check this,
> https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/50/files

now i've got this error:
       -TypeError: undefined is not an object (evaluating 'children.type.displayName')

i've copied index.js and overwrite the existing

**Comment by rhrahul** [comment]
@leoceolin , please check now, it should work now.
https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/50/files

and remember to use ScrollView as a direct child otherwise it won't work.

**Comment by leoceolin** [comment]
> @leoceolin , please check now, it should work now.
> https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/50/files
> 
> and remember to use ScrollView as a direct child otherwise it won't work.

closeOnDragDown worked now but Scroll doesn't yet.

here is my code:

`return (
      <View style={{flex: 1}}>
        <MapView
          showsUserLocation
          style={{flex: 1}}
          mapType='satellite'
          initialRegion={this.state.region}
          cacheEnabled
          region={this.state.region}
          /* provider={PROVIDER_GOOGLE} */
        >
          {this.state.pontosMarker.map(item => {
            return (
              <>
                <Marker
                  key={item.id}
                  title={item.title}
                  description={item.description}
                  coordinate={item.coordinates}
                  onPress={() => {
                    this.markerDetails(item.nomePonto)
                  }}
                />
              </>
            )
          })}
          
        </MapView>

        <RBSheet
          ref={ref => {
            this.RBSheet = ref
          }}
          closeOnDragDown
          customStyles={{
            mask: {backgroundColor: 'transparent'},
            container: {
              elevation: 100,
              height: 350,
              borderTopLeftRadius: 20,
              borderTopRightRadius: 20,
              backgroundColor: '#f7f5eee8',
            },
            draggableIcon: {
              backgroundColor: '#00000040',
            },
          }}>
          <TouchableOpacity
            onPress={() => this.RBSheet.close()}
            style={styles.dateHeaderButton}>
            <Icon name='clear' size={35} style={{color: '#c60000'}} />
          </TouchableOpacity>
          <View style={styles.messageContainerTitle}>
            <Text style={styles.messageTitle}>
              Ponto: {this.state.nomePonto}
            </Text>
          </View>
          <ScrollView>
            <View>
              <View
                style={{
                  justifyContent: 'center',
                  textAlign: 'center',
                  flexDirection: 'row',
                }}>
                <Text>
                  <Text style={{fontWeight: 'bold'}}>Fazenda:</Text>{' '}
                  {this.state.fazenda}
                </Text>
                <Text style={{marginLeft: 5}}>
                  <Text style={{fontWeight: 'bold'}}>| Talhão:</Text>{' '}
                  {this.state.talhao}
                </Text>
              </View>
              {this.state.pontoSelecionado.map(res => {
                // const coords = JSON.parse(res.coordinates)
                const date = this.formatDate(res.date)
                if (res.fullInfo.tipoNC !== undefined) {
                  return (
                    <View key={res.date} style={styles.messageContainer}>
                      <View style={styles.message}>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Data:</Text> {date}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Praga:</Text>{' '}
                          {res.pragueName}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>
                            Plantas analisadas:
                          </Text>{' '}
                          {res.plantasAtacadas}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>
                            Plantas atacadas:
                          </Text>{' '}
                          {res.plantasAnalisadas}
                        </Text>
                      </View>
                      <View style={styles.lineWithPlants} />
                    </View>
                  )
                } else {
                  return (
                    <View key={res.date} style={styles.messageContainer}>
                      <View style={styles.message}>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Data:</Text> {date}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Praga:</Text>{' '}
                          {res.pragueName}
                        </Text>
                        <Text>
                          <Text style={{fontWeight: 'bold'}}>Quantidade:</Text>{' '}
                          {res.quantity}
                        </Text>
                      </View>
                      <View style={styles.line} />
                    </View>
                  )
                }
              })}
            </View>
          </ScrollView>
        </RBSheet>
      </View>
    )`

**Comment by rhrahul** [comment]
Ok, I made it only for one ScrollView child and you are using View and TouchableOpacity with it.
This is interesting, I'll work on it and find a solution.

**Comment by leoceolin** [comment]
> Ok, I made it only for one ScrollView child and you are using View and TouchableOpacity with it.
> This is interesting, I'll work on it and find a solution.

Thank's man, if i can help with anything, reply here !

**Comment by rhrahul** [comment]
Hi,
I updated file with solution for now, I am not sure if it's proper solution or not, but it does the job.
https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/50/files

**Comment by nysamnang** [comment]
Hello @leoceolin @rhrahul, as you can see everything is working fine in my example. I'm not able to use your snippet code to test, so could you please create a new simple snippet to reveal it doesn't work?
