### ISSUE TITLE
Visual bug when closing down

### ISSUE THREAD

**Issue by acerbastimur** [nysamnang/react-native-raw-bottom-sheet#51]
Hi, when I'm closing the component it stucks at the position I stopped dragging for a few miliseconds and jumps before closing.

My code :
`
<RBSheet
          ref={ref => {
            CampaignDetailsModalStore.campaignDetailsHalfModalRef = ref;
          }}
          duration={450}
          closeOnDragDown
          animationType="slide"
          customStyles={{ 
            container: {
              borderTopRightRadius: 40,
              borderTopLeftRadius: 40,
              paddingTop: 2,
              height: 'auto',
              shadowOffset: {width: 0, height: 2},
              shadowColor: '#000',
              shadowOpacity: 0.2,
            },
            draggableIcon: {width: 100, height: 4, backgroundColor: Colors.SECONDARY},
          }}>
          <CampaignDetails navigation={navigation} />
        </RBSheet>`
![ezgif-5-ddb759723c97](https://user-images.githubusercontent.com/33218120/74195468-538ab680-4c6c-11ea-8940-c27c80d66d7f.gif)

**Comment by acerbastimur** [comment]
I can see that the issue is about height:"auto", how can i solve this ?

**Comment by acerbastimur** [comment]
I changed my code into this :
` height={(Dimensions.get('window').height / 100) * 70}
          animationType="slide"
          duration={250}
          closeOnPressBack
          closeOnDragDown
          customStyles={{
            container: {
              borderTopRightRadius: 40,
              borderTopLeftRadius: 40,
              paddingTop: 2,
            },
            draggableIcon: {width: 100, height: 4, backgroundColor: Colors.SECONDARY},
          }}`


But now it stops for a second on Android.


![ezgif-5-4f84001207af](https://user-images.githubusercontent.com/33218120/74217309-26fc8c00-4cb8-11ea-9a3d-fac3fee445de.gif)

**Comment by nysamnang** [comment]
@acerbastimur Duplicate Question & Duplicate Author #44  😄

**Comment by ManuEpi** [comment]
Hello, I have the same problem , with animationType set to "none" and with `wrapper: { backgroundColor: 'transparent' }`

**Comment by shamshirgreyskymedia** [comment]
I am facing the same issue.Clicking on background, the view is perfectly sliding down. But when draging down  the view showing this issue.
`<RBSheet
      onClose={onClose}
      ref={refRBSheet}
      animationType="slide"
       closeOnDragDown={true}
       closeOnPressMask={true}
      customStyles={{
        container: {
          backgroundColor: 'transparent',
          paddingHorizontal: 15,
          height: 'auto',
        },
      }}>
      <View
        style={[styles.contentView]}
       >
        {props.children}
      </View>
    </RBSheet>`
    
    The behaviour only happens if the height is 'auto' and animation is 'slide'. If we provide a static height or animation to 'none', it works perfectly.
