### ISSUE TITLE
Support for bottom sheet header?

### ISSUE THREAD

**Issue by zack1eboy** [nysamnang/react-native-raw-bottom-sheet#57]
Is there a way of always displaying part of the bottom sheet?

Thanks,
Zack

**Comment by nysamnang** [comment]
@zack1eboy Why don't you add your own header component?
Example:

```
<RBSheet>
  <View>
    <Header />
    <Content />
  </View>
</RBSheet>
```

**Comment by Dimasprog** [comment]
Try to add `draggableIcon: { width: '100%', height: 20, borderRadius: 0, marginTop: 0 }`
