### ISSUE TITLE
Ability to tap View/s behind bottom sheet

### ISSUE THREAD

**Issue by nickmccomb** [nysamnang/react-native-raw-bottom-sheet#58]
Is there a way to be able to tap components that are behind the open bottom sheet?  E.g pointerEvents: 'none' for the container component?

**Comment by nysamnang** [comment]
@nickmccomb I can simply say NO because RBSheed is built on top of React Native Modal. Sorry for inconvenient.

**Comment by nickmccomb** [comment]
All good!  Thanks for the quick response!
