### ISSUE TITLE
How to adapt to iPhone X/XS/XR?

### ISSUE THREAD

**Issue by lucianomlima** [nysamnang/react-native-raw-bottom-sheet#6]
When have a BottomSheet that have more than 260 of height, the last item stay under the virtual home button of the related devices.

Is there a way to give some space from bottom?

I did try use `SafeAreaView` from `react-navigation` but doesn't work.
Maybe if there a prop `WrapperComponent` that accepts a component to use, fix the problem.

**Comment by nysamnang** [comment]
@lucianomlima If the last item stay under the virtual home button, I wonder why don't you add more height to BottomSheet?

**Comment by lucianomlima** [comment]
Because this only can be done for the devices need it. And now React Native Api only allow to check what platform is.

I think this is an issue with lib.
For example, the component react-native-keyboard-accessory have a prop to adjust itself when inside a SafeAreaView.

https://github.com/ardaogulcan/react-native-keyboard-accessory

**Comment by ikhattab** [comment]
@nysamnang can we re-open this one, please 🙏

**Comment by manawaraquevix** [comment]
Any update about this. I am also facing.

**Comment by lokomass** [comment]
Any update about this. I am also facing.

**Comment by bfaulk96** [comment]
I use
`customStyles={{ container: { paddingBottom: BOTTOM_SHEET_PADDING_BOTTOM } }}`
where `BOTTOM_SHEET_PADDING_BOTTOM` is `MY_PADDING + getBottomSpace()`
and `getBottomSpace()` is from the [react-native-iphone-x-helper](https://github.com/ptelad/react-native-iphone-x-helper) library.. Not the most elegant solution, but it's what we've got right now haha

**Comment by NN01010101** [comment]
Please reopen. Since it is an issue. <SafeAreaView> should be applicable to child views.
