### ISSUE TITLE
RBSheet placed behind Overlay on IOS

### ISSUE THREAD

**Issue by whileMeAwakeMeCode** [nysamnang/react-native-raw-bottom-sheet#61]
Hi, 
First, thank you for this awesome package !

I use react-native-elements Overlay component in my project and RBSheet opens as expected when this Overlay is visible on android but it looks that it's placed behind (invisible) on ios. 

I tried to set the zIndex with an absolute position but it still doesn't work :/ 
If I close the overlay before the message is fired, then its displaying.

I'd like to end up with the android behavior for both platforms.

Any idea ?

**Comment by whileMeAwakeMeCode** [comment]
Ok finally the overlay doesnt hide anything... it's just about state update, async job and device memory. 

You can close the case.

**Comment by brunolcarlos** [comment]
I have the same issue, on IOS the overlay it's over the child item
