### ISSUE TITLE
publish 2.1.0?

### ISSUE THREAD

**Issue by wadehuang36** [nysamnang/react-native-raw-bottom-sheet#64]
I saw 2.1.0 added keyboardAvoidingViewEnabled. However, the latest version on npm is 2.0.6. That would be awsome if we can have it 2.1.0 on npm.

Thanks for your hard work. we use your component a lot in our works.

**Comment by nysamnang** [comment]
There you go https://github.com/nysamnang/react-native-raw-bottom-sheet/releases/tag/2.1.0 !!
