### ISSUE TITLE
closeOnDragDown should be tied to props

### ISSUE THREAD

**Issue by KjellConnelly** [nysamnang/react-native-raw-bottom-sheet#65]
Hey guys,

So I got a nice `raw-bottom-sheet` showing up with a UI that allows the user to make an in-app-purchase. I don't want the user navigating outside of the `raw-bottom-sheet` while the process is happening, so I want to disable `closeOnDragDown` (the pan responder) while this is happening. Of course, I still want closeOnDragDown set to true while the user in not mid-purchase. 

Any way you could make the changes to make this tied to the component's props, and not just initial props?

![Simulator Screen Shot - iPhone 8 - 2020-03-20 at 10 19 38](https://user-images.githubusercontent.com/13230597/77189335-a427d780-6a94-11ea-86c2-c8393eadef81.png)

**Comment by nysamnang** [comment]
```jsx
state = {
   isAllowCloseOnDragDown: fasle
}
```
```jsx
if (condition === true) {
  this.setState({ isAllowCloseOnDragDown: true });
}
```
```jsx
<RBSheet closeOnDragDown={this.state.isAllowCloseOnDragDown} >
```

@KjellConnelly Doesn't this simple code work?

**Comment by KjellConnelly** [comment]
I'm pretty sure I tried something like that, but no it doesn't. I believe a panhandler is connected when the object is being constructed. But when you change state, the panhandler will not emerge into existance if it doesn't already exist, nor will it disappear.

**Comment by dagi3d** [comment]
+1
I'm in a similar situation where I would like to prevent the user from closing it after some state changes.
I have something like

```
const { allowClose } = this.state;
  <RBSheet
        ref={sheet => this.sheet = sheet}
        duration={250}
        closeOnDragDown={allowClose}
        closeOnPressBack={allowClose}
        closeOnPressMask={allowClose}
        open>
{children}
</RBSheet
```

when the state changes, the `closeOnPressBack` and `closeOnPressMask` work as expected, that is, closing is not allowed, but it allows to drag it down and close it.

**Comment by kashif-sk** [comment]
+1 facing the same issue
@KjellConnelly @dagi3d did u find any workaround for this ?
