### ISSUE TITLE
popup menu on bottom sheet component click not working

### ISSUE THREAD

**Issue by prashantopenxcell** [nysamnang/react-native-raw-bottom-sheet#66]
When i try to open the popup menu on click of bottom sheet button component, it show the menu behind the bottom sheet. so how  can i achive it.?

**Comment by nysamnang** [comment]
Hello @prashantopenxcell, It's not possible to achieve this behaviour because `RBSheet` is implemented on top of React Native Modal. When the Modal open, we absolutely could not press any component behind the Modal. Sorry for inconvenient.
