### ISSUE TITLE
React Native <View> doesn't work inside the RBSheet

### ISSUE THREAD

**Issue by vigneshkb07** [nysamnang/react-native-raw-bottom-sheet#67]
components which is enclosed by View react native component is not rendered properly

**Comment by nysamnang** [comment]
@vigneshkb07 Could you provide some example code?

**Comment by eduramme** [comment]
I came across the same problem. When I create the component with Views wrapping other components (styling purposes), the onPress functionality on TouchableOpacity doesn't work (and it seems to not recognize anything inside the View, styles work properly though)

`<RBSheet
        ref={refRBSheet}
        height={450}
        minClosingHeight={50}
        duration={350}
        closeOnDragDown={true}
        closeOnPressMask={false}>
        <View style={styles.flatlist}>
          <Text style={styles.collectionText}>Title</Text>
          <View style={styles.collections}>
            <TouchableOpacity
              onPress={() => console.log('working')} /* doesn't work */
              style={styles.collectionContainer}>
              <MyComponent />
            </TouchableOpacity>
          </View>
        </View>
      </RBSheet>`

When I take the Views out, it suddenly starts working again

`<RBSheet
        ref={refRBSheet}
        height={450}
        minClosingHeight={50}
        duration={350}
        closeOnDragDown={true}
        closeOnPressMask={false}>
          <Text style={styles.collectionText}>Title</Text>
            <TouchableOpacity
              onPress={() => console.log('working')}
              style={styles.collectionContainer}>
              <MyComponent />
            </TouchableOpacity>
      </RBSheet>`

**Comment by eduramme** [comment]
I came across the same problem. When I create the component with Views wrapping other components (styling purposes), the onPress functionality on TouchableOpacity doesn't work (and it seems to not recognize anything inside the View, styles work properly though)

```
<RBSheet
        ref={refRBSheet}
        height={450}
        minClosingHeight={50}
        duration={350}
        closeOnDragDown={true}
        closeOnPressMask={false}>
        <View style={styles.flatlist}>
          <Text style={styles.collectionText}>Title</Text>
          <View style={styles.collections}>
            <TouchableOpacity
              onPress={() => console.log('working')} /* doesn't work */
              style={styles.collectionContainer}>
              <MyComponent />
            </TouchableOpacity>
          </View>
        </View>
</RBSheet>

```
When I take the Views out, it suddenly starts working again

```
<RBSheet
        ref={refRBSheet}
        height={450}
        minClosingHeight={50}
        duration={350}
        closeOnDragDown={true}
        closeOnPressMask={false}>
          <Text style={styles.collectionText}>Title</Text>
            <TouchableOpacity
              onPress={() => console.log('working')}
              style={styles.collectionContainer}>
              <MyComponent />
            </TouchableOpacity>
</RBSheet>
```
