### ISSUE TITLE
React Native Modal is not showing in IOS

### ISSUE THREAD

**Issue by gayucode** [nysamnang/react-native-raw-bottom-sheet#68]
I am using RBSheet to show some of the menu items. If the user clicks the menu it will open a modal.
it's working fine in android but in IOS it's not showing the modal.
I tried removing the RBSheet and tested it. It's working fine in android and IOS. 
The below screenshot is ref behavior in android
![image](https://user-images.githubusercontent.com/25306452/77869789-63327e80-725d-11ea-9ece-d4e2756a69f8.png)
The below screenshot is ref behavior in ios
![image](https://user-images.githubusercontent.com/25306452/77869812-71809a80-725d-11ea-9c9a-a3afc8f36fba.png)
You can see that inside state modalVisible is returning false for open and close in IOS but in android, it returns true for open and false for close

**Comment by nysamnang** [comment]
Hello @gayathri-perumal, Have you tried to put the Modal inside `<RBSheet>` ?
**Example:**
```jsx
<RBSheet>
  <YourOwnComponentOne  />
  <Modal>
    <YourOwnComponentTwo />
  </Modal>
</RBSheet>
```
Hope this could help.

**Comment by gayathri-perumal** [comment]
@nysamnang I tried. The modal is shown for 1 sec and hide.

**Comment by hanifmhd** [comment]
> @nysamnang I tried. The modal is shown for 1 sec and hide.

same for me, need solution for this

**Comment by gayucode** [comment]
The above issue is resolved after wrapping the component correctly

[exmaple project](https://snack.expo.io/3Od6z!qyu)

And I am closing this issue.

**Comment by siddharthJadhav** [comment]
Is it possible to put modal outside the RBSheet? Because if I put the modal inside RBSheet then the model will display inside the RBSheet and it will not consume all the screen.

I want to open the modal with the entire screen.

**Comment by Hamawis** [comment]
This woked for me.
```
<Modal>
  <Text>A</Text>
  <RbSheet>
    <Text>B</Text>
  </RbSheet>
</Modal>
```

**Comment by Amir5003** [comment]
opening new popup and closing previous popup was working fine in android i tried settimeout in iOS it is now working in iOS too...


                   if(Platform.OS === 'ios'){
                    setTimeout(() => {
                      this.RBSheetRef2.open();
                    }, 200);
                    this.RBSheetRef1.close();
                  }
                  else{
                    this.RBSheetRef2.open();
                    this.RBSheetRef1.close();
                  }
