### ISSUE TITLE
Customize status bar?

### ISSUE THREAD

**Issue by hrahimi270** [nysamnang/react-native-raw-bottom-sheet#7]
Hi.
Thanks for this amazing Bottom sheet!
I'm customized my status bar on my routes.
But, when I open the bottom sheet, my status bar color changes.
Can you provide a prop for the package that we put the status bar config for the openned bottom sheet?

Regards.

**Comment by nysamnang** [comment]
`RBSheet` used react native `Modal` to make a pop up component, so i don't think there is any conflict between `RBSheet` and the `StatusBar`.

There are 2 ways to set status bar color:
1. Place `<StatusBar backgroundColor="blue" />` component inside render method
2. Call StatusBar method` StatusBar.setBackgroundColor("blue");`

See react native [StatusBar](https://facebook.github.io/react-native/docs/statusbar) for more detail and sorry for late reply.
