### ISSUE TITLE
How to handle multiple content on our Bottom Sheet ?

### ISSUE THREAD

**Issue by ManuEpi** [nysamnang/react-native-raw-bottom-sheet#71]
Hello , thanks for the library it works pretty fine.

I have an issue here , I would like to use the Bottom Sheet with different content , in order to make like a navigation, using functional components

**What I want to do ?** 
I'm on the first Bottom Sheet and I click on a button inside it , it opens a new Bottom Sheet (or the same but with different content ?) replacing the first one . And when I go back , the first Bottom Sheet re-open with his datas ( like in a navigation stack )

The problem is that we have to know for each Bottom Sheet, the reference in order to make `reference.open(), reference.close()`, it's particularly complicated to handle multiple ref I think .

Is it possible to keep the same Bottom Sheet but to change ONLY the content inside ? 

Thanks

**Comment by ManuEpi** [comment]
The issue is resolved.

I created a BaseBottomSheet functional component : 

`function BaseModal(props) {

    function getCurrentModal(type) {
        switch (type) {

            case Constants.ALERT_MODAL_MAIN_SELECTION: {
                return <MainAlertModal hideModalCallback={props.hideModalCallback}
                                       onModalChangedCallback={props.onModalChangedCallback}/>

            }
            case Constants.ALERT_MODAL_V_SELECTION: {
                return <ViolenceModal hideModalCallback={props.hideModalCallback}
                                      onModalChangedCallback={props.onModalChangedCallback}/>
            }
        }
    }

    return (
        <View>
            {
                props.isModalOpened ? getCurrentModal(props.type) : null
            }
        </View>

    );
}`

Which is called like that in my Home screen : (using Hooks variable)
`<BaseModal type={typeOfModal} isModalOpened={isAlertModalVisible} hideModalCallback={hideAlertModalCallback} onModalChangedCallback={onModalChangedCallback}/>`

Every custom component will have the callback onModalChanged , that will change the type of Modal and then re-render BaseModal with the given type

**Comment by aravi365** [comment]
How did you managed it ? @ManuEpi
