### ISSUE TITLE
React Native v0.62 requires useNativeDriver to be explicitly declared

### ISSUE THREAD

**Issue by kyiii** [nysamnang/react-native-raw-bottom-sheet#72]
Getting this warning when the sheet animates: 

> Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by dephiros** [comment]
Related to https://github.com/nysamnang/react-native-raw-bottom-sheet/issues/77

**Comment by nysamnang** [comment]
#78
