### ISSUE TITLE
Close from a child component

### ISSUE THREAD

**Issue by nipunravisara** [nysamnang/react-native-raw-bottom-sheet#73]
I'm using a different form component as a content of react-native-raw-bottom-sheet. I'm trying to close the bottom-sheet from that form component submit button. Any possible way to do that ?

**Comment by nikndr** [comment]
@RavisaraDev You just need to forward ref to that child component. Check out these docs https://reactjs.org/docs/forwarding-refs.html

**Comment by will-districtnerds** [comment]
I'm not very experienced with forward ref. Is there an example of how one would forward ref RBSheet to a child component?
