### ISSUE TITLE
How to add a custom icon to draggableIcon?

### ISSUE THREAD

**Issue by dhuber666** [nysamnang/react-native-raw-bottom-sheet#74]
Hiho,

first and foremost, awesome project!

Is there a way to define my own draggable Icon on the Sheet?
Something so it looks like this:

![mystyle](https://user-images.githubusercontent.com/15130832/78669234-41c83700-78dc-11ea-9c48-a84be5c2037d.PNG)

This would be the last piece, so I can start to build. If it's not already in there somehow, I might try to implement it and send in a pull request. 

Greets from Austria,
Geralt

**Comment by alz10** [comment]
go to folder `node_modules > react-native-raw-bottom-sheet > src > index.js`

find and replace this code
```
{closeOnDragDown && (
    <View
      {...dragFromTopOnly && this.panResponder.panHandlers}
      style={styles.draggableContainer}
    >
          {this.props.customDraggableIcon}
           {/* <View style={[styles.draggableIcon, customStyles.draggableIcon]} /> */}
           </View>
 )}
```

then use it like this in a prop
```
<ActionSheet customDraggableIcon={<Text>Your Custom Draggable Icon</Text>} />
```

**Comment by NitishQuovantis** [comment]
You can apply transparent background to the draggle icon and absolutely position your icon in the sheet. 

   draggableIcon: {
          backgroundColor: 'transparent',
          height: 30,
          width: '100%',
        },
