### ISSUE TITLE
Purpose of minimum closing height

### ISSUE THREAD

**Issue by bharathy-kannan** [nysamnang/react-native-raw-bottom-sheet#79]
Hi,

I am not sure what the purpose of the minimum closing height is. I want the sheet to remain fixed at a certain height so that I can pull it back again. Is there a way to do this? Right now the sheet goes inside completely and I have to click a button to bring it back again. Instead, I want a portion to remain fixed at the bottom.

Thanks
Bharathy

**Comment by magnusfernandes** [comment]
+1

**Comment by shekharskamble** [comment]
+1

**Comment by Incedo0808** [comment]
Yes I want same feature to fix closing height of sheet to pull it back. Please help.

**Comment by umer-viabletree** [comment]
+1

**Comment by minafa96** [comment]
Just go ahead and use react-native-modalize!

**Comment by Dani-Boy92** [comment]
+1

**Comment by nysamnang** [comment]
Moved to #80
