### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by crashtimer** [nysamnang/react-native-raw-bottom-sheet#8]
First of all: thank you! you did great job!

Can you please add typings for this module? A lot of people use typescript nowadays.

Appreciate your efforts. Thanks

**Comment by sirajalam049** [comment]
Same here. Thanks for opening this issue @crashtimer

**Comment by nysamnang** [comment]
PRs Welcome because i'm not familiar with Typescript :D

**Comment by Grohden** [comment]
@nysamnang @sirajalam049 @crashtimer maybe this could help?

```typescript
import { ViewStyle } from 'react-native'

declare module 'react-native-raw-bottom-sheet' {
    
    type RBSheetProps = {
        animationType?: 'none' | 'fade' | 'slide'
        height?: number
        minClosingHeight?: number
        duration?: number
        closeOnSwipeDown?: boolean
        closeOnPressMask?:boolean
        onClose?: () => void
        customStyles?: {
            wrapper?: ViewStyle
            container?: ViewStyle
        }
    }

    declare class RBSheet extends React.Component<RBSheetProps> {
        open(): void
        close(): void
    }

    export default RBSheet
}
```

**Comment by sirajalam049** [comment]
#12

**Comment by Amir5003** [comment]
> @nysamnang @sirajalam049 @crashtimer maybe this could help?
> 
> ```ts
> import { ViewStyle } from 'react-native'
> 
> declare module 'react-native-raw-bottom-sheet' {
>     
>    export type RBSheetProps = {
>         animationType?: 'none' | 'fade' | 'slide'
>         height?: number
>         minClosingHeight?: number
>         duration?: number
>         closeOnSwipeDown?: boolean
>         closeOnPressMask?:boolean
>         onClose?: () => void
>         customStyles?: {
>             wrapper?: ViewStyle
>             container?: ViewStyle
>         }
>     }
> 
>     declare class RBSheet extends React.Component<RBSheetProps> {
>         open(): void
>         close(): void
>     }
> 
>     export default RBSheet
> }
> ```
> 
> Edit: use the one from my PR anyway

children?: React.JSX.Element;   this also can be included?

**Comment by Ranvijay-DCTech** [comment]
I am Still getting the Same error ?? 

please tell me exact Steps to be followed
Thanks

**Comment by Ranvijay-DCTech** [comment]
> > @nysamnang @sirajalam049 @crashtimer maybe this could help?
> > ```ts
> > import { ViewStyle } from 'react-native'
> > 
> > declare module 'react-native-raw-bottom-sheet' {
> >     
> >    export type RBSheetProps = {
> >         animationType?: 'none' | 'fade' | 'slide'
> >         height?: number
> >         minClosingHeight?: number
> >         duration?: number
> >         closeOnSwipeDown?: boolean
> >         closeOnPressMask?:boolean
> >         onClose?: () => void
> >         customStyles?: {
> >             wrapper?: ViewStyle
> >             container?: ViewStyle
> >         }
> >     }
> > 
> >     declare class RBSheet extends React.Component<RBSheetProps> {
> >         open(): void
> >         close(): void
> >     }
> > 
> >     export default RBSheet
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Edit: use the one from my PR anyway
> 
> children?: React.JSX.Element; this also can be included?
> 
> i faced below issue while using react-native-raw-bottom-sheet in tsx and it worked post I add children?: React.JSX.Element;
> 
> ![Screenshot from 2023-05-28 17-28-14](https://private-user-images.githubusercontent.com/35360244/241558347-dc693fe6-10e1-43ce-85b4-13ecba47cd4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzEwOTQsIm5iZiI6MTcwNjQzMDc5NCwicGF0aCI6Ii8zNTM2MDI0NC8yNDE1NTgzNDctZGM2OTNmZTYtMTBlMS00M2NlLTg1YjQtMTNlY2JhNDdjZDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA4MzMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMjJhOTYxYWQzNjNiZTVhODYyOTA1OGFjOWJkMGE4YWNmZmVkNDA0MTc4YzE5MGE4NzQ0YTY1MGQ2MWMzZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VnoNXAC_lSQpcJpEOcdp-mHv1lNRMMgsa4wuoLp5MrA)

Where Did you added 
children?: React.JSX.Element;

??????
