### ISSUE TITLE
Allow drag up to open/expand 

### ISSUE THREAD

**Issue by crobinson42** [nysamnang/react-native-raw-bottom-sheet#80]
This is a great component, simple api and a joy to use. Is there any plan to allow "snap points" similar to: https://github.com/osdnk/react-native-reanimated-bottom-sheet?

Also, the ability to `dragUpToExpand` prop would be fantastic, thoughts?

**Comment by neoncloth** [comment]
+1

**Comment by Steffi3rd** [comment]
+100

**Comment by tanveersalmangkn** [comment]
Bring this feature and this will be the best repo <3
Hope this will be added asap

**Comment by magnusfernandes** [comment]
+1

**Comment by drummerjolev** [comment]
+1

**Comment by Epiczzor** [comment]
+1
Would have used it on my project, but I need the drag up to expand

**Comment by sorxrob** [comment]
Here's an awesome component if you want snapping

https://github.com/rgommezz/react-native-scroll-bottom-sheet

**Comment by ShivamJoker** [comment]
I also need this feature there are other libraries but they are dependent on reanimated

**Comment by xwg2015** [comment]
+1
