### ISSUE TITLE
How to animate BackDrop mask?

### ISSUE THREAD

**Issue by Steffi3rd** [nysamnang/react-native-raw-bottom-sheet#84]
Hi,

Currently, the backdrop is display or hide without any animation.
I would like to add a simple fade in/out animation on the backdrop. 

I didn't find a way to do that.

Is it possible?

**Comment by miczed** [comment]
I don't think that's possible in the current implementation. I think it would be possible if the underlying implementation of the <Modal> element would be switched to the [community edition](https://github.com/react-native-community/react-native-modal) that supports the animation of the backdrop. 

@nysamnang is there a particular reason you used the official (and less verbose) implementation of the modal? If not I could try to switch the implementation and create a PR for it.

**Comment by joeyfigaro** [comment]
@miczed did you you end up making any progress on this?

**Comment by miczed** [comment]
No, I haven‘t had the time to look into it yet. I can probably find time next week, it shouldn‘t be too much work

--

**Comment by itzyashh** [comment]
Hi can we have control over both the animation because when slide animation is used both backdrop and sheet use the same animation it looks good on sheet but the back drop should have fade or none animation @nysamnang
