### ISSUE TITLE
Dynamic height for sheet

### ISSUE THREAD

**Issue by ercane** [nysamnang/react-native-raw-bottom-sheet#9]
Hi, thanks for this great job. Is there a way to make the height dynamic?

**Comment by nysamnang** [comment]
@ercane You can get height from your child component by using `onLayout` then pass it RBSheet.

**Comment by Grohden** [comment]
@nysamnang if I'm not wrong, RB animations are based on height, so I think that using onLayout will not work (at least it didn't work for me)

To solve my problem and get a dynamic height I've changed the component to use only translation animations.. heres a gist with my work:
https://gist.github.com/Grohden/8a343451614aa96747d7ba5cedc993b0

I still have to change some values (on the `onPanResponderRelease`) and improve some other stuff (like using velocity and adding a snap behavior)... could RB use this approach?

**Comment by ntkzwane** [comment]
Is this more in line of getting the RBSheet to assume the height of the child/content, or to be able to change the height of an existing RBSheet? I'm having issues with the latter i.e changing the `height` prop of an open RBSheet does not change its height (it's always fixed to the initial value of the prop). Is this intended behaviour?

PS: If this issue is targeted at the former, I'm happy to move the discussion onto a new issue.

**Comment by kelokchan** [comment]
Here is what I have done to have dynamic height
```
      customStyles={{
        container: {
          ...styles.container,
          height, // <-- a state
        },
      }}>
```

But doing it this way to cause the animation to disappear

**Comment by chris-chao** [comment]
Hi, has there been any update on this? 

I am wanting to make the height change dynamic, such as when a user opens an RBSheet, then clicks a button inside that RBSheet, the height of that same Sheet should adjust instantly. 

I am able to set height as a state and change the value but it only shows the changed height after the user closes the sheet then opens it back up again.

**Comment by fend25** [comment]
btw, there is PR and there is advice to use `open()` to set new height)
https://github.com/nysamnang/react-native-raw-bottom-sheet/pull/82#issuecomment-647122023

**Comment by tarunsoni96** [comment]
One Reliable solution i made.. 

Go to index.js of library code

1. Add this function

`setHeight(height){
    if(!this.state.height)
    setTimeout(() => {
      this.setState({height},()=>this.setModalVisible(true, this.props))
    },0);
  }`

2. Replace the "open" function with :

`open(props) {
    this.setState({modalVisible:true})
    if(this.state.height){
      this.setModalVisible(true, props);
    } 
  }`

3. Add state variable - height and set it o, and replace the height var from props to state in "setModalVisible" function so it gets height from state

4. Add `onLayout={e => this.setHeight(e.nativeEvent.layout.height) }` in Animated.View component

5. Replace Animate.view style with `style={[panStyle, styles.container, {opacity: this.state.height ? 1 : 0 , height: this.state.height ? animatedHeight : undefined }, customStyles.container]}`

6. Go styles.js of library code, replace container style with `container: {
    backgroundColor: "#fff",
    width: "100%",
    overflow: "hidden"
  },`

Test and run!

**Comment by harshtyagimdr** [comment]
`Set the state const [height, setHeight] = useState(undefined);`
 <RBSheet
            customStyles={{
                container: {
                    height: height 
                },
            }}

        >
            <View onLayout={(e) => setHeight(e.nativeEvent.layout.height)}></View>
</RBSheet>
Copy and run.This will surely help to make the dynamic height for sheet

**Comment by shubhambathe1** [comment]
Based on @Grohden answer I came up with a simplified solution. Got a workaround for making Dynamic Bottomsheet and also not losing on the opening/closing animations. Have tested it on both platforms(android, iOS). React Native Version 0.62.2 & Bottomsheet Version 2.2.0. Here are the steps that I have followed:-

**Import Package For Responsive Screens, its optional**
```
import {
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

```
Setting the RB Sheet Reference
`const refRBSheet = useRef();`

Need to add these three additional states for Dynamic behaviour

BottomSheet Initial height state
`const [height, setHeight] = useState(hp(50));`

BottomSheet visible state
`const [visible, setVisible] = useState(false);`

Conditionally Rendering RB-Sheet Content
`const [component, setComponent] = useState('bottomsheet_content_1');`

Adding a useEffect for tracking refRBSheet & height
```
useEffect(() => {
    if (visible) {
      refRBSheet.current.open();
    } else {
      refRBSheet.current.close();
    }
  }, [refRBSheet, height]);
```

toggleDrawer method to open bottomsheet with specified component/content
 ```
 const toggleDrawer = (componentName) => {
    // Setting Component to be displayed
    setComponent(componentName);

    // Switch case for dynamic height based on component selected
    switch (componentName) {
      case 'bottomsheet_content_1':
        setHeight(hp(100));
        break;
      case 'bottomsheet_content_2':
        setHeight(hp(85));
        break;
      case 'bottomsheet_content_3':
        setHeight(hp(60));
        break;
      case 'bottomsheet_content_4':
        setHeight(hp(45));
        break;
      default:
        setHeight(hp(50));
    }

    // Setting Visible state & Opening RBSheet
    setVisible(!visible);
    refRBSheet.current.open();
  };
```

**Now the code for Dynamic RB Bottomsheet**
```
        <RBSheet
        ref={refRBSheet}
        height={height}
        openDuration={500}
        closeOnDragDown={false}
        closeOnPressMask
        closeOnPressBack
        closeOnSwipeDown={false}
        customStyles={{
          container: styles.rbSheetContainer,
          wrapper: styles.rbSheetWrapper,
          draggableIcon: styles.rbSheetDragIcon,
        }}
        onClose={() => setVisible(false)}
      >
        {component === 'bottomsheet_content_1' ? (
          <Component1
            props={props}
            drawerClose={() => refRBSheet.current.close()}
          />
        ) : component === 'bottomsheet_content_2' ? (
          <Component2
            props={props}
            drawerClose={() => refRBSheet.current.close()}
          />
        ) : component === 'bottomsheet_content_3' ? (
          <Component3
            props={props}
            drawerClose={() => refRBSheet.current.close()}
          />
        ) : component === 'bottomsheet_content_4' ? (
          <Component4
            props={props}
            drawerClose={() => refRBSheet.current.close()}
          />
        ) : (
          <DefaultComponent
            props={props}
            drawerClose={() => refRBSheet.current.close()}
          />
        )
        }
      </RBSheet>
```

Finally to open the RB Sheet for any click event use the toggleDrawer method and pass it appropriate component name to render height dynamically based on it.

`onPress={() => toggleDrawer('bottomsheet_content_1')}`
To open component with height as hp(100) full window height.

`onPress={() => toggleDrawer('bottomsheet_content_2')}`
To open component with height as hp(80) 80% of window height.

Hope this helps...!!

**Comment by narohan** [comment]
A solution that does not lose any functionality and very simple.

`import React, { useRef, useState } from "react";
import { View, Button, Text } from "react-native";
import RBSheet from "react-native-raw-bottom-sheet";

export default function Example() {

  const [heightBottomSheet, setHeightBottomSheet] = useState(0)
  const [ready, setReady] = useState(false)
  const refRBSheet = useRef()

  if(!ready) { 
    return <Text style={{fontSize: 18, backgroundColor: "green", padding: 10}} onLayout={(event) => {
      const height = event.nativeEvent.layout.height
      setHeightBottomSheet(height)
      setReady(true)
    }}>Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le mondeBonjour tout le monde, Bonjour tout le monde</Text>
  } else {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: "#000"
        }}>
        <Button title="OPEN BOTTOM SHEET" onPress={() => refRBSheet.current.open()} />
        <RBSheet
          ref={refRBSheet}
          closeOnDragDown={true}
          closeOnPressMask={false}
          height={heightBottomSheet}
          customStyles={{
            wrapper: {
              backgroundColor: "transparent"
            },
            draggableIcon: {
              backgroundColor: "#000"
            }
          }}>
          <Text style={{fontSize: 10, padding: 10}}>Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le mondeBonjour tout le monde, Bonjour tout le monde</Text>
        </RBSheet>
      </View>
    )
  }
}`

**Comment by Csutkas** [comment]
> A solution that does not lose any functionality and very simple.
> 
> ```
> import { View, Button, Text } from "react-native";
> import RBSheet from "react-native-raw-bottom-sheet";
> 
> export default function Example() {
> 
>   const [heightBottomSheet, setHeightBottomSheet] = useState(0)
>   const [ready, setReady] = useState(false)
>   const refRBSheet = useRef()
> 
>   if(!ready) { 
>     return <Text style={{fontSize: 18}} onLayout={(event) => {
>       const height = event.nativeEvent.layout.height
>       setHeightBottomSheet(height)
>       setReady(true)
>     }}>Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le mondeBonjour tout le monde, Bonjour tout le monde</Text>
>   } else {
>     return (
>       <View
>         style={{
>           flex: 1,
>           justifyContent: "center",
>           alignItems: "center",
>           backgroundColor: "#000"
>         }}>
>         <Button title="OPEN BOTTOM SHEET" onPress={() => refRBSheet.current.open()} />
>         <RBSheet
>           ref={refRBSheet}
>           closeOnDragDown={true}
>           closeOnPressMask={false}
>           height={heightBottomSheet}
>           customStyles={{
>             wrapper: {
>               backgroundColor: "transparent"
>             },
>             draggableIcon: {
>               backgroundColor: "#000"
>             }
>           }}>
>           <Text style={{fontSize: 18}}>Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le monde, Bonjour tout le mondeBonjour tout le monde, Bonjour tout le monde</Text>
>         </RBSheet>
>       </View>
>     )
>   }
> }
> ```

With this solution you will se the bottom sheet for a very little time when the base component is rendering. :(

**Comment by Csutkas** [comment]
I can solve the flashing problem (due to first render) if I add this style to the rendered container:
```
renderContainerStyle: {
    position: 'absolute',
    bottom: -2000
  }
```
  
  
  e.g.:

```
if(!ready) { 
    return 
    <View style={styles.renderContainerStyle} onLayout={(event) => {
      const height = event.nativeEvent.layout.height
      setHeightBottomSheet(height)
      setReady(true)
    }}>
        <Text>Bonjour tout le monde</Text>
    </View>
  } else 
```

**Comment by mswarraich10** [comment]
> Here is what I have done to have dynamic height
> 
> ```
>       customStyles={{
>         container: {
>           ...styles.container,
>           height, // <-- a state
>         },
>       }}>
> ```
> 
> But doing it this way to cause the animation to disappear

It worked for me. Thanks.

**Comment by gunkiddedy** [comment]
> Set the state `const [height, setHeight] = useState(undefined);` ` <RBSheet customStyles={{ container: { height: height }, }} > <View onLayout={(e) => setHeight(e.nativeEvent.layout.height)}></View> </RBSheet>` Copy and run.This will surely help to make the dynamic height for sheet

thanks so much, dude! this works for me.

**Comment by theodoremca** [comment]
See what we have here. Too good to be true. You just need to pass null to the height.

      customStyles={{
        container: {
          height: null
        },
