### ISSUE TITLE
Bottom sheet animation doesn't work with "height: 'auto'"

### ISSUE THREAD

**Issue by FranciscoCHT** [nysamnang/react-native-raw-bottom-sheet#92]
I have a simple bottom sheet mounted with fade animation setting, and I'm trying to set the height of it according to the content. It works with setting the container style with height: 'auto' (like the code below), but that cancels the slide bottomsheet animation totally, it justs fades away a second later. Is there a way to do this?

`customStyles={{
     container: {
         height: 'auto',
         maxHeight: 300,
     }
}}`

**Comment by dagan-arbox** [comment]
egger issue! 
please update.

**Comment by alexandrepletty** [comment]
Add `animationType` the animation will be less raw while waiting for an update
