### ISSUE TITLE
Clicking on hardware back button on Android closes the sheet

### ISSUE THREAD

**Issue by obendevski** [nysamnang/react-native-raw-bottom-sheet#93]
Hey,

Even though I  have both closeOnDragDown={false} closeOnPressMask={false}, the back button on Android still closes the raw sheet.
Even if I catch the event with BackHandler and return true, it still closes it. 
Not sure where to look anymore. Help please :)

**Comment by amitasaurus** [comment]
Add `closeOnPressBack={false}`
