### ISSUE TITLE
Please add param for open

### ISSUE THREAD

**Issue by VictorPulzz** [nysamnang/react-native-raw-bottom-sheet#95]
It would be nice if the default open option was added. This is very convenient if you have delayed component rendering. 
Something like this: 
![image](https://user-images.githubusercontent.com/23406402/84875514-b95dd380-b08e-11ea-9589-90ab6e1e3f5c.png)

**Comment by brayhoward** [comment]
You can easily add this yourself in your project or submit a PR to this project

<img width="551" alt="Screen Shot 2020-07-10 at 11 25 40 AM" src="https://user-images.githubusercontent.com/10436515/87177057-a52d8080-c2a0-11ea-8dc1-da678329f29e.png">

**Comment by VictorPullzz** [comment]
Hmmm @brayhoward, open pass props, sounds good. I will try this, thank you! :)
