### ISSUE TITLE
ScrollView or FlatList inside is not working

### ISSUE THREAD

**Issue by Brijesh59** [nysamnang/react-native-raw-bottom-sheet#97]
Hey, I added a scrollview inside the bottom sheet, and the screen froze while opening the bottom sheet. Although there is scrolling, but onPress is not working and screen kind of freezes.
I tried using Flatlist, but the issue remains the same.

**Comment by rgaba** [comment]
I had a similar issue and had to wrap the View with <TouchableWithoutFeedback>

**Comment by rgaba** [comment]
Sorry, just realized it didn't work... needs to be wrapped with `<TouchableWithoutFeedback>`

**Comment by rodribech20** [comment]
I have same issue. I am using on ScrollView, it works  first time but after it does not work more. Any solution? Thanks

**Comment by rizwanellahi** [comment]
Facing the same issue, ScrollView is only working with the mouse wheel in the virtual device. The physical device it's not working.

**Comment by mertlena** [comment]
i faced with same problem, then when i set `closeOnDragDown={false}` it is working now.

**Comment by lissau** [comment]
You can use `closeOnDragDown={true}` if you also enable `dragFromTopOnly={true}`

**Comment by raazatul7** [comment]
and update?
I'm using expo
Flatlist scroll and touch is not working in Android.

**Comment by Yashnandha** [comment]
flatlist and ScrollView Both Not Working At the time

**Comment by rgaba** [comment]
> 

Have you tried wrapping your View with <TouchableWithoutFeedback> imported from react-native?

**Comment by novaladip** [comment]
it's working for me when I set dragFromTopOnly={true} without wrapping my component with TouchableWithoutFeedback component


```jsx
<RBSheet
   ref={modalRef}
   closeOnDragDown={true}
   dragFromTopOnly={true}
   closeOnPressMask={true}
   height={height * 0.6}>
      <Component />
</RBSheet>
```

**Comment by DishaBoleFaiz** [comment]
> ```js
> closeOnDragDown={true}
>    dragFromTopOnly={true}
>    closeOnPressMask={true}
> ```

Worked....

**Comment by Tobi-Julius** [comment]
setting this to false worked for me
  dragOnContent={false} 
  
  i hope it does work for you
